databases:
  - name: fatrecipe_db
    databaseName: fat_recipe
    user: sakamoto_kohei_44
    region: singapore

services:
  - type: web
    name: Fat_Recipe
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fatrecipe_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false